### ISSUE TITLE
Functions to add

### ISSUE THREAD

**Issue by VinciGit00** [studio-YOLO/editpix#2]
- Light
- Exposition
- Highlights
- Shadows
- Saturation
- Tint
- Sharpness
- Definition

**Comment by f-aguzzi** [comment]
A little recap on the state of this issue:

**Fully completed (coded in `core`, exposed through `EditPix`)**:
- Brightness
- Saturation

**Implemented in `core` but not in EditPix**:
- Shadows
- Sharpness

**Completely missing**:
- Exposure
- Highlights
- Tint
- Definition

**Comment by VinciGit00** [comment]
Hi, I created exposure and tint in core

**Comment by VinciGit00** [comment]
Fully completed (coded in core, exposed through EditPix):

- [ ] Brightness
- [ ] Saturation

Implemented in core but not in EditPix:

- [ ] Shadows
- [ ] Sharpness
- [ ] Tint

Completely missing:

- [ ]  Exposure
- [ ]  Highlights
- [ ]  Definition
